### ISSUE TITLE
BinaryHash/CodeHash 0x prefix

### ISSUE THREAD

**Issue by ashchan** [nervosnetwork/ckb-sdk-swift#62]
Does it has `0x` prefix ?

_Originally posted by @classicalliu in https://github.com/nervosnetwork/ckb-sdk-swift/pull/53_

**Comment by classicalliu** [comment]
RPC 接口是全部要求 `0x` 开头的，十六进制的字符串如果没有这个 prefix 会报错

**Comment by ashchan** [comment]
Things to check:

- [ ] `codeHash`
- [ ] `H256.zeroHash`
- [ ] `Script.alwaysSuccessHash`

**Comment by ashchan** [comment]
> RPC 接口是全部要求 `0x` 开头的，十六进制的字符串如果没有这个 prefix 会报错

Thanks for the info. Then we should always prefix them.
